### ISSUE TITLE
Attempting to import a TF2 uncompiled map, getting a wall of errors

### ISSUE THREAD

**Issue by Gamepro5** [H2xDev/GodotVMF#1]
Here are the errors I am getting:
![image](https://github.com/H2xDev/GodotVMF/assets/23440295/a7170a4d-69c7-4422-b87c-2f2d9eef181f)
![image](https://github.com/H2xDev/GodotVMF/assets/23440295/07089ee8-acd2-44ad-805b-6c0dd09b78a9)

Here is what my config looks like:

```json
{
	"entitiesFolder": "res://examples/entities",
	"gameInfoPath": "C:/Program Files (x86)/Steam/steamapps/common/Team Fortress 2",
	"instancesFolder": "res://examples/instances",
	"materialsFolder": "res://examples/materials",
	"mdl2obj": "res://mdl2obj.exe",
	"modelsFolder": "res://examples/models",
	"nodeConfig": {
		"defaultTextureSize": 512,
		"fallbackMaterial": null,
		"generateCollision": true,
		"generateCollisionForModel": true,
		"ignoreTextures": [
			"TOOLS/TOOLSNODRAW"
		],
		"importModels": false,
		"importScale": 0.025,
		"overrideModels": true,
		"textureImportMode": 1
	},
	"vtflib": "C:/Program Files/Nem's Tools/VTFEdit"
}
```
I am using Godot 4.2.1 stable.

The map I tried importing is [this](https://dcff.short.gy/ctf_pelican_peak_d).

**Comment by H2xDev** [comment]
Hello!

I'd suggest you to resave the VMF in [Hammer++](https://ficool2.github.io/HammerPlusPlus-Website/), since the VMF doesn't contain precised vertex data (`vertices_plus` data inside of brushes). The vanilla version of Hammer is not supported yet.

Also you have wrong `gameInfoPath` in the config. `C:/Program Files (x86)/Steam/steamapps/common/Team Fortress 2/tf2` will be correct.

**Comment by Gamepro5** [comment]
![image](https://github.com/H2xDev/GodotVMF/assets/23440295/a3aaa384-b72a-4d43-9c6c-003182f36f05)
![image](https://github.com/H2xDev/GodotVMF/assets/23440295/2cc23b20-4fc0-4224-b8fd-59fe653bf776)

Hi, Thanks for the quick reply. I fixed the path and re-exported it in hammer++ (ALT+B). It is drawing some stuff now but it is drawing all of the invisible player clip brushes and doesn't seem to find any of the materials. Do I need to convert each individual one into a TRES and put it in my example folder?

For TF2, the materials are located in a VPK.

**Comment by H2xDev** [comment]
@Gamepro5 
As I mentioned in [Readme](https://github.com/H2xDev/GodotVMF/?tab=readme-ov-file#known-issues), exporting resources from VPKs are not supported yet. To import all materials you need to extract all materials from VPKs in the `tf2` folder first.

**Comment by Gamepro5** [comment]
@H2xDev Thanks again. Extracting the VPK into the game's directory still doesn't fix the complaining that it does about there not being any .TRES files. Do I need to find a program that can recursively convert each VTF from the exported directory into TRES, and then put an exact replica of that folder of converted TRES into my Godot directory?

**Comment by H2xDev** [comment]
@Gamepro5 Check `textureImportMode` in the config. It should be `2`

**Comment by Gamepro5** [comment]
@H2xDev Sorry for bothering you again. I re-read the installation page 3 times just to be absolutely sure I didn't miss anything. I keep getting the yellow warnings that the materials TRES is not found. It doesn't seem to be generating them. Did it work on your end?

![image](https://github.com/H2xDev/GodotVMF/assets/23440295/e5099826-2788-44f8-a5e7-24395c87ca14)

```json
{
	"entitiesFolder": "res://resources/entities",
	"gameInfoPath": "C:/Program Files (x86)/Steam/steamapps/common/Team Fortress 2/tf2",
	"instancesFolder": "res://resources/instances",
	"materialsFolder": "res://resources/materials",
	"mdl2obj": "c:/mdl2obj.exe",
	"modelsFolder": "res://resources/models",
	"nodeConfig": {
		"defaultTextureSize": 512,
		"fallbackMaterial": null,
		"generateCollision": true,
		"generateCollisionForModel": true,
		"ignoreTextures": [
			"TOOLS/TOOLSNODRAW"
		],
		"importModels": false,
		"importScale": 0.025,
		"overrideModels": true,
		"textureImportMode": 2
	},
	"vtflib": "C:/Program Files/Nem's Tools/vtflib132-bin/bin/x64/VTFCmd.exe"
}

```

**Comment by H2xDev** [comment]
@Gamepro5 
What if you change the config like that?
```diff
- "gameInfoPath": "C:/Program Files (x86)/Steam/steamapps/common/Team Fortress 2/tf2",
+ "gameInfoPath": "C:/Program Files (x86)/Steam/steamapps/common/Team Fortress 2/tf",
```

**Comment by H2xDev** [comment]
@Gamepro5 
So, I updated the plugin and now texture import should work. Download the plugin from the repository and try again.

Change the vmf.config.json:
```diff
- "gameInfoPath": "C:/Program Files (x86)/Steam/steamapps/common/Team Fortress 2/tf2",
+ "gameInfoPath": "C:/Program Files (x86)/Steam/steamapps/common/Team Fortress 2/tf",
```

**Comment by Gamepro5** [comment]
It works partially. Some textures are showing up, but it is still complaining that it can't find some vmt files that are clearly there.
![image](https://github.com/H2xDev/GodotVMF/assets/23440295/9b925da3-baf2-4701-80da-673369a368df)

**Comment by Gamepro5** [comment]
Also, this might be a different issue but the ignoreTextures parameter isn't working to ignore stuff like TOOLS/CLIP, TOOLS/HINT, etc.

**Comment by Gamepro5** [comment]
> Also you can add all tool textures into the `ignoreTextures` in the config after then faces with these materials will be ignored.

This might be a seperate issue but I know that I listed the right names and it stills renders the HINT brushes and all other brushses.
```json
"ignoreTextures": [
			"tools/toolsblack",
			"tools/toolsclip",
			"tools/toolsskip",
			"tools/toolsskybox",
			"tools/toolsnpcclip",
			"tools/toolstrigger",
			"tools/toolshint",
			"tools/toolsfog"
		],
```
![image](https://github.com/H2xDev/GodotVMF/assets/23440295/84c250ca-d0f4-4bc9-93cf-634252e2d863)
![image](https://github.com/H2xDev/GodotVMF/assets/23440295/c8f0fc2a-095a-484e-a308-9fe21ee8498a)

**Comment by H2xDev** [comment]
@Gamepro5 
> It fails to convert some of them but doesn't say that they aren't found in the directory.
I guess VTFCmd couldn't convert these textures into PNG for some reason. Also TF2 depends on some materials from HL2 VPKs. Try to extract them into `tf` folder as well.

> This might be a seperate issue but I know that I listed the right names and it stills renders the HINT brushes and all other brushses.
Looks like i forgot to add case check. Try to convert these texture names to upper case. I'll fix that soon

**Comment by Gamepro5** [comment]
> Looks like i forgot to add case check. Try to convert these texture names to upper case. I'll fix that soon

But the names aren't uppercase in the directory.
