### ISSUE TITLE
Incomplete material data.

### ISSUE THREAD

**Issue by SharkPetro** [H2xDev/GodotVMF#17]
Material importer ignores VMT properties other than $basetexture and VTF data other than the single image that is the base texture.

The biggest issue is the lack of mip texture export. Even with VTFs where mip textures are included, the importer ignores them.

It would be great if the most used properties changed Godot material properties such as $translucent turning transparency from disabled to alpha.

**Comment by H2xDev** [comment]
@SharkPetro 
Implemented native VTF support. Check [feature/VTFTool](https://github.com/H2xDev/GodotVMF/tree/feature/VTFTool) and give a try :)

**Comment by H2xDev** [comment]
@SharkPetro 
Good. I fixed these problems i think. 

About blendtextures. There need a separate material shader for it that can have two textures. I already implemented the shader but i need to create a new BaseMaterial3D resource that will work this this shader and use it during import. Actually i don't really know how to implement it now.

**Comment by SharkPetro** [comment]
I am stupid, sorry, clicking buttons accidentally, I didn't mean to close the issue.

Everything works good except transparency does not get applied to any materials at all and detail blend mode is all wrong.

Though to implement detail maps as they work in source there needs to be another custom shader. `$detailblendmode` parameter defines what exactly the detail map does.
Most materials use `"$detailblendmode" 0` which is a simple brightness effect. Colors below 128 darken the image, colors above brighten it. This mode is used on bricks and concrete alike, but most notably on damage impact decals, they are the reason textures don't look like blobby mess in valve games as the albedo maps themselves are pretty blurry.
`1` is additive.
`2` is a translucent detail map that gets drawn on top with transparency in consideration.
`3` is the same as 2 but now instead of alpha, the blend value is used for transparency.

There's also mipblend parameter that controls the way detail maps interact with mip textures.

But these are just some examples, I think for now it'll be good enough to have one blend mode `"$detailblendmode" 0` which most valve made materials use. It'll be a very long time until you implement the entire material system as it is in source so an approximation is good enough.

Thank you for this update, the mipmaps alone are enough to make up for all else, and I have few enough transparent materials for it not to be an issue.

**Comment by H2xDev** [comment]
Could you share the map you trying to import? I’d like to use it as test case :)

**Comment by SharkPetro** [comment]
Sure thing. Github doesn't support this file type so here's google drive link: https://drive.google.com/file/d/1uXSS8ys_J-BdhOkxnxVrX4pnQ8rIYgnc/view?usp=drive_link.

It uses only Half Life 2 textures, all of which I stole from the game files.
