### ISSUE TITLE
Incomplete model import.

### ISSUE THREAD

**Issue by SharkPetro** [H2xDev/GodotVMF#21]
I'm sorry for the long hold, I had trouble with college that I had to deal with first. Good job on improving the plugin by the way, I'm immensely happy with how nicely it's coming along.

Here's a list of issues and enhancement proposals for the model and material import:

- Most MDL models have a separate collision model that is not used by GodotVMF and instead a convex collision shape is generated that sometimes does not resemble the model at all. This is most noticeable with trees and grass. Trees get collision that includes their branches and results in a huge area to be inaccessible under the tree instead of just it's trunk being solid. Most props that would normally not be solid at all as for not having a collision model at all, like grass, now have a huge collider that gets in the way.
- Model skins not supported.
- prop_static's Collisions property in hammer is ignored. All settinigs use the generated collision model instead of the one included in the MDL for `Use VPhysics`, nothing for `Not solid` or a bounding box for `Use bounding box`.
- I know it would take a while but it still would be nice to import animations and include an animation player with prop_static entities as well because some models have an actual animation as their idle sequence, as well as some models like combine doors having several animations for opening/closing ect. I kinda want to test if I can just use hl2 viewmodels and character world models and their animations.
- `props_combine/stasisvortex.mdl` is missing transparency.
- `items/ammocrate_smg1.mdl` and `props_c17/tv_monitor01.mdl` have weird artifacts.
- Some materials wrongfully have backface culling while others wrongfully don't.
Examples:
`props_combine/combine_booth_short01a.mdl` glass on the front is only visible from the inside, on the sides is only visible from the outside.
`props_c17/paper01.mdl` is invisible from the bottom.
material `metal/metalfence007a` is not backface culled but it should be.

Another thing, it's probably a dumb question but I want to know if it's even possible to somehow have shaders from the materials translated to compute shaders that can be used in Godot with any sort of accuracy, if at all.

**Comment by H2xDev** [comment]
For this issue we probably need full support of MDL format which is pretty complex task i believe. For me at least.

> Another thing, it's probably a dumb question but I want to know if it's even possible to somehow have shaders from the materials translated to compute shaders that can be used in Godot with any sort of accuracy, if at all.

The class `VMT` of `VTFTool.gd` has material mapping property `materialMap` where you can assign an another material class instead of StandardMaterial3D for specific shader as it made for `WorldVertexTransition` for blend textures. Need to create analogies of shaders from Source Engine and i suppose it should solve the problem with materials completely. For sure it's a complex task as well.
