### ISSUE TITLE
Add documentation for using on linux

### ISSUE THREAD

**Issue by nonunknown777** [H2xDev/GodotVMF#28]
This seems to be a very promising project, I use linux, and as you guys may know hammer++ doesnt work on it, unless used with wine, but also having HL2 and steam seems to be a requirement, could a tutorial/workaround be provided?

**Comment by H2xDev** [comment]
Hello @nonunknown777!
I did some investigation and unfortunately Hammer++ tightly attached to Source Engine base and can't be run independently.

**Comment by nonunknown777** [comment]
I saw that theres a linux replacement which is J.A.C.K I think maybe thats could be a replacement?

**Comment by H2xDev** [comment]
> I saw that theres a linux replacement which is J.A.C.K I think maybe thats could be a replacement?

J.A.C.K is for GoldSrc engine (HL1, CS)

**Comment by nonunknown777** [comment]
ohhh didnt know

**Comment by Leniptic** [comment]
> This seems to be a very promising project, I use linux, and as you guys may know hammer++ doesnt work on it, unless used with wine, but also having HL2 and steam seems to be a requirement, could a tutorial/workaround be provided?

Hammer++ works fine under Linux if you run it under Proton. I'm not sure what the issue is. Unless you specifically don't have Half Life 2 and Steam. Steam is free and Half Life 2 is 99 cents as of time of writing. There's not really a workaround needed.
