### ISSUE TITLE
Where can I find another copy of mdl2obj?

### ISSUE THREAD

**Issue by Lachrymogenic** [H2xDev/GodotVMF#3]
Hello, I am a developer working on a game in the Godot Game Engine and it was truly strange to me that your project was announced literally just a day before I got started on making the project I intended on making now, gotta say, that's pretty handy. On the other side of things though, I am a Linux user and have been trying to acquire the most native files that I can get to get started, so far I have gotten BSPSrc, VPKEdit, VTFCmd with Wine but as to where I can find another copy of mdl2obj I am somewhat completely stumped.

It's not as if I don't trust you or anything, but I'm personally wondering where mdl2obj.exe comes from, how it works, etc. I plan for players of my game to be able to create levels in VMF files and load them at runtime, but them requiring all of these tools and having to set all of it up is somewhat of a pain, luckily for some tools like VTFCmd, I know where certain links are and I know what licenses certain softwares use, like BSPSrc is public domain, which is great! But mdl2obj?

Where did you get that, exactly, did you make it? Is it related to https://github.com/fzwoch/mdl2obj ?
What license is it, can I compile a native version of it for Linux? Can I look at it's source code? I am very keen on learning the ins and outs of the source engine and as far as I have searched, I cannot seem to find it.

If you have any information, please let me know :)

**Comment by H2xDev** [comment]
Hello @Lachrymogenic 

Yes. This is important. 
I made this tool during work on GodotVMF. I forgot to upload it, sorry. I prepared a repo for this tool:
https://github.com/H2xDev/mdl2obj

It requires NodeJS 18+ to build and also don't have Linux support to build. It's not to had to add it i think.
