### ISSUE TITLE
CS:GO models do not import

### ISSUE THREAD

**Issue by JamDoggie** [H2xDev/GodotVMF#33]
As far as I can tell, CS:GO models do not import at all.

**Steps to reproduce:**

1. Download CS2
2. Opt into the beta branch "csgo_legacy", let it download.
3. Navigate to YOUR_STEAM_DIRECTORY/steamapps/common/Counter-Strike Global Offensive/csgo (do NOT navigate to Counter-Strike Global Offensive/game, this is the CS2 folder which contains Source 2 VPKs and is not relevant here).
4. Extract the models & materials folder from the dir VPK with GCFScape.
5. Extract whatever map you want to decompile if you want here too.
6. Decompile any map using the latest version of BSPSRC.
7. Import with GodotVMF.

**Expected results:**
GodotVMF should import all level geometry and prop models.

**Actual results:**
Map imports with no models but does import level geometry.

**Comment by H2xDev** [comment]
@JamDoggie Hello!

CS:GO has improved version of MDL which is not supported by MDL2OBJ utility i suppose. That's why you have no models in your imported map.

I currently working on native MDL import for GodotVMF which will support CS:GO models as well (i hope).

**Comment by JamDoggie** [comment]
Great to hear! In the meantime, I wonder if there are any tools for downgrading mdl files as a workaround.

**Comment by Ambiabstract** [comment]
> Great to hear! In the meantime, I wonder if there are any tools for downgrading mdl files as a workaround.

Hi! I'm not sure if there is a ready tool that allows you to downgrade MDL files to Source 2013.
Most likely Crowbar can handle this task, but you will have to decompile and then compile the required models. 
https://github.com/ZeqMacaw/Crowbar/releases

Maybe I'll get to write such a tool, but unfortunately not anytime soon
