### ISSUE TITLE
Instance Import

### ISSUE THREAD

**Issue by Whalee110** [H2xDev/GodotVMF#35]
After updating to GodotVMF 2.0a instances are no longer importing - initially there was issues because the path to VMFNode changed but after fixing those / deleting the old ones they are still failing to import.

The errors I get are below:
res://addons/godotvmf/src/VMFInstanceManager.gd:54 - Invalid operands 'int' and 'Nil' in operator '-'.
  core/variant/variant_utility.cpp:1100 - [GodotVMF] Failed to load instance: func_instance_12069

**Comment by H2xDev** [comment]
Fixed in 34a67ed
