### ISSUE TITLE
partially works on linux!

### ISSUE THREAD

**Issue by Dragon20C** [H2xDev/GodotVMF#4]
I have come from the reddit post and I mentioned on using linux, I have spent a few days on trying to get the hammer++ to work on linux and I finally got it working, now I have tested your plugin and it seems to work so far with basic geometry squares and rectangles (havent tested complex geometry yet) and it seems to work for that, but the textures dont seem to load in, though I am missing one third party dependency since it is an exe file I am not sure how it will work on the linux side.

**Comment by H2xDev** [comment]
Since I'm not a Linux user, I'm not sure how to help you with it. 
Sorry about that.

**Comment by Dragon20C** [comment]
I understand, I simply wanted to tell you it kinda works haha.

**Comment by H2xDev** [comment]
@Dragon20C Thank you :)
